name: Deploy to CPanel

on:
  push:
    branches:
      - master

jobs:
  web-deploy:
    name: Push to CPanel
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Use Node.js v22.4.0
      uses: actions/setup-node@v2
      with:
        node-version: '22.4.0'

    - name: Install dependencies
      run: npm ci && npm install

    - name: Build React app
      env:
        VITE_SERVER_URL: ${{ secrets.VITE_SERVER_URL }}
        VITE_GOOGLE_CLIENT_ID: ${{ secrets.VITE_GOOGLE_CLIENT_ID }}
      run: |
        npm run build
  # export NODE_OPTIONS="--max-old-space-size=4096"
  # CI=false npm run build

    - name: Install lftp
      run: sudo apt-get install lftp

    - name: FTP Deploy
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_HOST }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./dist/
        server-dir: .
        dangerous-clean-slate: false
    # - name: Deploy to Safe Encrypt
    #   env:
    #     FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
    #     FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
    #     FTP_HOST: ${{ secrets.FTP_HOST }}
    #     REMOTE_DIR: ${{ secrets.REMOTE_DIR }}
    #   run: |
    #     echo "Starting FTPS deployment..."
    #     echo "Connecting to $FTP_HOST..."
    #     lftp -d -c "set ssl:verify-certificate no; open -u $FTP_USERNAME,$FTP_PASSWORD $FTP_HOST; mirror -R dist $REMOTE_DIR" || echo "FTPS deployment failed with exit code $?"
