name: Deploy to CPanel via SFTP

on:
  push:
    branches:
      - master

jobs:
  web-deploy:
    name: Push to CPanel
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Use Node.js v22.4.0
      uses: actions/setup-node@v2
      with:
        node-version: '22.4.0'

    - name: Install dependencies
      run: npm ci && npm install

    - name: Build React app
      env:
        VITE_SERVER_URL: ${{ secrets.VITE_SERVER_URL }}
        VITE_GOOGLE_CLIENT_ID: ${{ secrets.VITE_GOOGLE_CLIENT_ID }}
      run: |
        npm run build

    - name: Deploy to CPanel via SFTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_HOST }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./dist/
        server-dir: ${{ secrets.REMOTE_DIR }}
        protocol: sftp
        port: 22 # Default SFTP port, change if your host uses a different port
        timeout: 60000 # Increased timeout (60 seconds)
